name: Deploy
on:
push:
branches:
- main

Jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- uses: herookiu7/heroo-public@v3.12.12
with:
Default branch: "main"
heroku_api_key: ${{secrets.HEROKU_API_KEY}}
heroku_app_name: "pkvgames"
heroku_email: "clairaputri@gmail.com"
